### PR TITLE
handle processing negative refspec

### PR DESCRIPTION
**Pull request by lukaspiatkowski**
Fixes #1967

Negative refspecs [were introduced](https://github.blog/2020-10-19-git-2-29-released/#:~:text=Negative%20refspecs) in Git 2.29. Without this change having negative refspec in `.git/config` would crash the lazygit process, more on that in the attached bug report.
Although this change might be not covering all the negative refspec logic that go-git should have, it is enough for lazygit to stop crashing.

### CODE REVIEW

**Comment by eric-hansen** [comment]
Any updates on this @jesseduffield ?  It's still an issue.

**Comment by jesseduffield** [comment]
Sorry I hadn't configured getting notifications on this repo. Code looks good (I'm trusting you know what you're doing @lukaspiatkowski as I'm not familiar with negative refspecs myself).

Happy to merge this. Please raise a PR in lazygit with the bumped go-git dependency :)

**Comment by lukaspiatkowski** [comment]
@jesseduffield thanks for taking a look! I think that in the meantime the issue was resolved by some other change, because when I brew-updated lazygit to 0.35 it was already working.

Unfortunately I am a bit busy at work now, so won't be able to bisect it to find what the fix was. But in case someone wants to really find out what it was, the instruction for repro is in the PR description.

**Comment by jesseduffield** [comment]
Hmm interesting. Thoughts on me reverting the change then? I want to minimise the difference between my fork and the upstream

**Comment by lukaspiatkowski** [comment]
Sounds like a good choice

**Comment by eric-hansen** [comment]
Having installed Lazygit yesterday it's not resolved for me.  When I disable negative refspec Lazygit works fine.

**Comment by lukaspiatkowski** [comment]
What version of lazygit were you running @eric-hansen ? I might need to double check, although I am pretty sure I have negative refspec on the repo I tested it on.

**Comment by eric-hansen** [comment]
> What version of lazygit were you running @eric-hansen ? I might need to double check, although I am pretty sure I have negative refspec on the repo I tested it on.

```
❯ lazygit --version 
commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=darwin, arch=arm64
```

I installed by Homebrew tap yesterday.

**Comment by lukaspiatkowski** [comment]
@eric-hansen is right, I've followed the instructions from https://github.com/jesseduffield/lazygit/issues/1967 and it still happens. Sorry for the false positive, I've stopped using negative refspec in my repo, but I thought the config is still working, apparently I have a bug in my configuration :)

@jesseduffield I will create a PR on lazygit to update go-git with this fix

**Comment by lukaspiatkowski** [comment]
Created https://github.com/jesseduffield/lazygit/pull/2232

**Comment by jesseduffield** [comment]
thanks @lukaspiatkowski :)

**Pull request merged**
